import { MODEL_FIELD_TYPES } from '../model/constants/modelFieldTypes';
import { ENTITY_KINDS } from '../../../shared/constants';

export const dataModelFields = [

  {
    id: 'fieldId-model0-name',
    kind: ENTITY_KINDS.DATA_MODEL_FIELD,
    type: MODEL_FIELD_TYPES.TEXT,
    modelId: 'model0',
    name: 'name',
    label: 'Name',
    isRequired: true,
  },
  {
    id: 'fieldId-model1-name',
    kind: ENTITY_KINDS.DATA_MODEL_FIELD,
    type: MODEL_FIELD_TYPES.TEXT,
    modelId: 'model1',
    name: 'name',
    label: 'Name',
    isRequired: true,

  },
  {
    id: 'fieldId-model1-email',
    kind: ENTITY_KINDS.DATA_MODEL_FIELD,
    type: MODEL_FIELD_TYPES.TEXT,
    modelId: 'model1',
    name: 'email',
    label: 'Email',
    isRequired: true,
  },
  {
    id: 'fieldId-model1-role',
    kind: ENTITY_KINDS.DATA_MODEL_FIELD,
    type: MODEL_FIELD_TYPES.REFERENCE,
    modelId: 'model1',
    name: 'role',
    label: 'Role',
    isRequired: true,
  },
  {
    id: 'fieldId-model1-slug',
    kind: ENTITY_KINDS.DATA_MODEL_FIELD,
    type: MODEL_FIELD_TYPES.TEXT,
    modelId: 'model1',
    name: 'slug',
    label: 'Slug',
    isRequired: true,
  },
  {
    id: 'fieldId-model1-createdAt',
    kind: ENTITY_KINDS.DATA_MODEL_FIELD,
    type: MODEL_FIELD_TYPES.DATE_TIME,
    modelId: 'model1',
    name: 'createdAt',
    label: 'Created',
    isRequired: false,
  },
  {
    id: 'fieldId-model1-avatar',
    kind: ENTITY_KINDS.DATA_MODEL_FIELD,
    type: MODEL_FIELD_TYPES.IMAGE,
    modelId: 'model1',
    name: 'avatar',
    label: 'Avatar',
  },
  {
    id: 'fieldId-model1-updatedAt',
    kind: ENTITY_KINDS.DATA_MODEL_FIELD,
    type: MODEL_FIELD_TYPES.DATE_TIME,
    modelId: 'model1',
    name: 'updatedAt',
    label: 'Updated',
    isRequired: false,
  },
  {
    id: 'fieldId-model2-name',
    kind: ENTITY_KINDS.DATA_MODEL_FIELD,
    type: MODEL_FIELD_TYPES.TEXT,
    modelId: 'model2',
    name: 'name',
    label: 'Name',
    isRequired: true,
  },
  {
    id: 'fieldId-model2-createdAt',
    kind: ENTITY_KINDS.DATA_MODEL_FIELD,
    type: MODEL_FIELD_TYPES.DATE_TIME,
    modelId: 'model2',
    name: 'createdAt',
    label: 'Created',
    isRequired: false,
  },
  {
    id: 'fieldId-model2-updatedAt',
    kind: ENTITY_KINDS.DATA_MODEL_FIELD,
    type: MODEL_FIELD_TYPES.DATE_TIME,
    modelId: 'model2',
    name: 'updatedAt',
    label: 'Updated',
    isRequired: false,
  },
];

