import type { ContextLink } from '../types';

export const contextLinks: ContextLink[] = [
  {
    id: 'contextLink-1',
    entityId: 'screen-01',
    entityType: 'screen',
    contextId: 'id-doc-1',
    contextType: 'document',
    relation: 'attached',
    createdBy: 'user-1',
    createdAt: '2024-03-28',
    updatedAt: '2024-03-28',
  },
  {
    id: 'contextLink-2',
    entityId: 'screen-01',
    entityType: 'screen',
    contextId: 'id-doc-2',
    contextType: 'document',
    relation: 'reference',
    createdBy: 'user-2',
    createdAt: '2024-03-28',
    updatedAt: '2024-03-28',
  },
  {
    id: 'contextLink-3',
    entityId: 'screen-02',
    entityType: 'screen',
    contextId: 'id-doc-3',
    contextType: 'document',
    relation: 'discussion',
    createdBy: 'user-3',
    createdAt: '2024-03-28',
    updatedAt: '2024-03-28',
  },
  {
    id: 'contextLink-4',
    entityId: 'id-workspace-1-project-1-task-1',
    entityType: 'task',
    contextId: 'id-doc-3',
    contextType: 'document',
    relation: 'discussion',
    createdBy: 'user-3',
    createdAt: '2024-03-28',
    updatedAt: '2024-03-28',
  },
  {
    id: 'contextLink-5',
    entityId: 'id-workspace-1-project-1-task-1',
    entityType: 'task',
    contextId: 'id-doc-5',
    contextType: 'document',
    relation: 'discussion',
    createdBy: 'user-3',
    createdAt: '2024-03-28',
    updatedAt: '2024-03-28',
  },
  {
    id: 'contextLink-6',
    entityId: 'id-workspace-1-project-1-task-1',
    entityType: 'task',
    contextId: 'chat-1',
    contextType: 'chat',
    relation: 'discussion',
    createdBy: 'user-3',
    createdAt: '2024-03-28',
    updatedAt: '2024-03-28',
  },

];
