import { ELEMENT_TAGS } from './elementTags';

export const ELEMENT_TYPES = {
  TEXT: 'text',
  BOX: 'box',
};

export const STYLE_TARGET_PROPERTY = {
  [ELEMENT_TAGS.PARAGRAPH]: ELEMENT_TYPES.TEXT,
  [ELEMENT_TAGS.HEADING1]: ELEMENT_TYPES.TEXT,
  [ELEMENT_TAGS.HEADING2]: ELEMENT_TYPES.TEXT,
  [ELEMENT_TAGS.HEADING3]: ELEMENT_TYPES.TEXT,
  [ELEMENT_TAGS.HEADING4]: ELEMENT_TYPES.TEXT,
  [ELEMENT_TAGS.HEADING5]: ELEMENT_TYPES.TEXT,
  [ELEMENT_TAGS.HEADING6]: ELEMENT_TYPES.TEXT,
  [ELEMENT_TAGS.SPAN]: ELEMENT_TYPES.TEXT,
  [ELEMENT_TAGS.LINK]: ELEMENT_TYPES.TEXT,
  [ELEMENT_TAGS.LABEL]: ELEMENT_TYPES.TEXT,

  [ELEMENT_TAGS.DIV]: ELEMENT_TYPES.BOX,
  [ELEMENT_TAGS.HEADER]: ELEMENT_TYPES.BOX,
  [ELEMENT_TAGS.FOOTER]: ELEMENT_TYPES.BOX,
  [ELEMENT_TAGS.SECTION]: ELEMENT_TYPES.BOX,
  [ELEMENT_TAGS.ARTICLE]: ELEMENT_TYPES.BOX,
  [ELEMENT_TAGS.ASIDE]: ELEMENT_TYPES.BOX,
  [ELEMENT_TAGS.MAIN]: ELEMENT_TYPES.BOX,
  [ELEMENT_TAGS.NAV]: ELEMENT_TYPES.BOX,

  // [ELEMENT_TAGS.BUTTON]: ELEMENT_TYPES.BOX,
  // [ELEMENT_TAGS.INPUT]: ELEMENT_TYPES.BOX,
  // [ELEMENT_TAGS.TEXTAREA]: ELEMENT_TYPES.BOX,
  // [ELEMENT_TAGS.SELECT]: ELEMENT_TYPES.BOX,
  // [ELEMENT_TAGS.FORM]: ELEMENT_TYPES.BOX,
};

export const getElementTypeByTag = (tag) => {
  if (!tag) {return ELEMENT_TYPES.BOX;}

  if (tag && STYLE_TARGET_PROPERTY[tag]) {
    return STYLE_TARGET_PROPERTY[tag];
  }
  return ELEMENT_TYPES.BOX;
};

export const getElementTagsByType = (type) => {
  if (!type) {return Object.values(ELEMENT_TAGS);}
  const tags = Object.keys(STYLE_TARGET_PROPERTY).filter(tag => STYLE_TARGET_PROPERTY[tag] === type);
  return tags;
};
