export const ELEMENT_TAGS = {
  BODY: 'body',

  PARAGRAPH: 'p',
  HEADING1: 'h1',
  HEADING2: 'h2',
  HEADING3: 'h3',
  HEADING4: 'h4',
  HEADING5: 'h5',
  HEADING6: 'h6',

  DIV: 'div',
  SPAN: 'span',
  HEADER: 'header',
  FOOTER: 'footer',
  SECTION: 'section',
  ARTICLE: 'article',
  ASIDE: 'aside',
  MAIN: 'main',
  NAV: 'nav',

  IMAGE: 'img',
  VIDEO: 'video',
  AUDIO: 'audio',
  LINK: 'a',
  IFRAME: 'iframe',
  BUTTON: 'button',
  LABEL: 'label',
  INPUT: 'input',
  TEXTAREA: 'textarea',
  SELECT: 'select',
  OPTION: 'option',
  FORM: 'form',
};
