import { ENTITY_KINDS } from '../../../shared/constants';
export const tokenValues = [
  {
    id: 'token-value-00',
    kind: ENTITY_KINDS.TOKEN_MODE_VALUE,
    tokenId: 'token-0',
    variableModeId: 'theme-mode-1-collection-1',
    value: '#FFFFFF',
  },
  {
    id: 'token-value-01',
    kind: ENTITY_KINDS.TOKEN_MODE_VALUE,
    tokenId: 'token-0',
    variableModeId: 'theme-mode-2-collection-1',
    value: '#111111',
  },
  {
    id: 'token-value-1',
    kind: ENTITY_KINDS.TOKEN_MODE_VALUE,
    tokenId: 'token-1',
    variableModeId: 'mode-1-color-token-collection-3',
    value: '#001122',
  },
  {
    id: 'token-value-2',
    kind: ENTITY_KINDS.TOKEN_MODE_VALUE,
    tokenId: 'token-2',
    variableModeId: 'mode-1-color-token-collection-3',
    value: '#001C38',
  },
  {
    id: 'token-value-3',
    kind: ENTITY_KINDS.TOKEN_MODE_VALUE,
    tokenId: 'token-3',
    variableModeId: 'mode-1-color-token-collection-3',
    value: '#004882',
  },
  {
    id: 'token-value-4',
    kind: ENTITY_KINDS.TOKEN_MODE_VALUE,
    tokenId: 'token-4',
    variableModeId: 'mode-1-color-token-collection-3',
    value: '#0060AA',
  },
  {
    id: 'token-value-5',
    kind: ENTITY_KINDS.TOKEN_MODE_VALUE,
    tokenId: 'token-5',
    variableModeId: 'mode-1-color-token-collection-3',
    value: '#0079D4',
  },
  {
    id: 'token-value-6',
    kind: ENTITY_KINDS.TOKEN_MODE_VALUE,
    tokenId: 'token-6',
    variableModeId: 'mode-1-color-token-collection-3',
    value: '#3293F4',
  },
  {
    id: 'token-value-7',
    kind: ENTITY_KINDS.TOKEN_MODE_VALUE,
    tokenId: 'token-7',
    variableModeId: 'mode-1-color-token-collection-3',
    value: '#6DAEFF',
  },
  {
    id: 'token-value-8',
    kind: ENTITY_KINDS.TOKEN_MODE_VALUE,
    tokenId: 'token-8',
    variableModeId: 'mode-1-color-token-collection-3',
    value: '#A3C9FF',
  },
  {
    id: 'token-value-9',
    kind: ENTITY_KINDS.TOKEN_MODE_VALUE,
    tokenId: 'token-9',
    variableModeId: 'mode-1-color-token-collection-3',
    value: '#D3E3FF',
  },
  {
    id: 'token-value-10',
    kind: ENTITY_KINDS.TOKEN_MODE_VALUE,
    tokenId: 'token-10',
    variableModeId: 'mode-1-number-token-collection-4',
    value: 24,
  },
  {
    id: 'token-value-11',
    kind: ENTITY_KINDS.TOKEN_MODE_VALUE,
    tokenId: 'token-11',
    variableModeId: 'mode-1-number-token-collection-4',
    value: 28,
  },
  {
    id: 'token-value-12',
    kind: ENTITY_KINDS.TOKEN_MODE_VALUE,
    tokenId: 'token-12',
    variableModeId: 'mode-1-number-token-collection-4',
    value: 32,
  },
  {
    id: 'token-value-13',
    kind: ENTITY_KINDS.TOKEN_MODE_VALUE,
    tokenId: 'token-13',
    variableModeId: 'mode-1-string-token-collection-5',
    value: 'Your focus determines your reality',
  },

];
