// Global attributes are attributes common to all HTML elements.
export const GLOBAL_ATTRIBUTES = [
  { id: 'id-global-accessKey', jsxName: 'accessKey', htmlName: 'accesskey' },
  { id: 'id-global-aria-*', jsxName: 'aria-*', htmlName: 'aria-*' },
  { id: 'id-global-autocapitalize', jsxName: 'autocapitalize', htmlName: 'autocapitalize' },
  { id: 'id-global-autoFocus', jsxName: 'autoFocus', htmlName: 'autofocus' },
  { id: 'id-global-className', jsxName: 'className', htmlName: 'class' },
  { id: 'id-global-contentEditable', jsxName: 'contentEditable', htmlName: 'contenteditable' },
  { id: 'id-global-data-*', jsxName: 'data-*', htmlName: 'data-*' },
  { id: 'id-global-dir', jsxName: 'dir', htmlName: 'dir' },
  { id: 'id-global-draggable', jsxName: 'draggable', htmlName: 'draggable' },
  { id: 'id-global-enterKeyHint', jsxName: 'enterKeyHint', htmlName: 'enterkeyhint' },
  { id: 'id-global-hidden', jsxName: 'hidden', htmlName: 'hidden' },
  { id: 'id-global-id', jsxName: 'id', htmlName: 'id' },
  { id: 'id-global-inert', jsxName: 'inert', htmlName: 'inert' },
  { id: 'id-global-inputMode', jsxName: 'inputMode', htmlName: 'inputmode' },
  { id: 'id-global-is', jsxName: 'is', htmlName: 'is' },
  { id: 'id-global-lang', jsxName: 'lang', htmlName: 'lang' },
  { id: 'id-global-nonce', jsxName: 'nonce', htmlName: 'nonce' },
  { id: 'id-global-part', jsxName: 'part', htmlName: 'part' },
  { id: 'id-global-popover', jsxName: 'popover', htmlName: 'popover' },
  { id: 'id-global-role', jsxName: 'role', htmlName: 'role' },
  { id: 'id-global-slot', jsxName: 'slot', htmlName: 'slot' },
  { id: 'id-global-spellCheck', jsxName: 'spellCheck', htmlName: 'spellcheck' },
  { id: 'id-global-style', jsxName: 'style', htmlName: 'style' },
  { id: 'id-global-tabIndex', jsxName: 'tabIndex', htmlName: 'tabindex' },
  { id: 'id-global-title', jsxName: 'title', htmlName: 'title' },
  { id: 'id-global-translate', jsxName: 'translate', htmlName: 'translate' },
];
