// Коннекторы для API
export const connectors = [
  {
    id: 'connector-1',
    name: 'Connector 1',
    authentication: 'Bearer Token',
    keyName: 'api_key',
    keyValue: 'your_api_key',
    headersIds: ['header-1'],
    parametersIds: ['param-1'],
    callsIds: ['call-1'],
  },
  {
    id: 'connector-2',
    name: 'Connector 2',
    authentication: 'Basic Auth',
    keyName: 'username',
    keyValue: 'user',
    headersIds: [],
    parametersIds: [],
    callsIds: [],
  },
  {
    id: 'connector-10',
    name: 'CMS API',
    authentication: 'API Key',
    keyName: 'cms_api_key',
    keyValue: '',
    headersIds: [],
    parametersIds: [],
    callsIds: [],
  },
  {
    id: 'connector-11',
    name: 'Collaboration API',
    authentication: 'OAuth',
    keyName: 'collab_token',
    keyValue: '',
    headersIds: [],
    parametersIds: [],
    callsIds: [],
  },
  {
    id: 'connector-12',
    name: 'Developer Tools API',
    authentication: 'Bearer Token',
    keyName: 'dev_token',
    keyValue: '',
    headersIds: [],
    parametersIds: [],
    callsIds: [],
  },
  {
    id: 'connector-13',
    name: 'Documents API',
    authentication: 'API Key',
    keyName: 'doc_api_key',
    keyValue: '',
    headersIds: [],
    parametersIds: [],
    callsIds: [],
  },
  {
    id: 'connector-14',
    name: 'SEO API',
    authentication: 'API Key',
    keyName: 'seo_api_key',
    keyValue: '',
    headersIds: [],
    parametersIds: [],
    callsIds: [],
  },
  {
    id: 'connector-15',
    name: 'Payment API',
    authentication: 'API Key',
    keyName: 'payment_api_key',
    keyValue: '',
    headersIds: [],
    parametersIds: [],
    callsIds: [],
  },
  {
    id: 'connector-16',
    name: 'Marketing API',
    authentication: 'OAuth',
    keyName: 'marketing_token',
    keyValue: '',
    headersIds: [],
    parametersIds: [],
    callsIds: [],
  },
  {
    id: 'connector-17',
    name: 'Analytics API',
    authentication: 'Bearer Token',
    keyName: 'analytics_token',
    keyValue: '',
    headersIds: [],
    parametersIds: [],
    callsIds: [],
  },
];
