import {
  EVENT_HANDLER_ATTRIBUTES,
  GLOBAL_ATTRIBUTES,
  VIDEO_TAG_ATTRIBUTES,
  AUDIO_TAG_ATTRIBUTES,
  A_TAG_ATTRIBUTES,
  BUTTON_TAG_ATTRIBUTES,
  IFRAME_TAG_ATTRIBUTES,
  FORM_TAG_ATTRIBUTES,
  IMG_TAG_ATTRIBUTES,
  INPUT_TAG_ATTRIBUTES,
} from './attrs';


export const htmlAttrs = [
  ...GLOBAL_ATTRIBUTES,
  ...EVENT_HANDLER_ATTRIBUTES,
  ...VIDEO_TAG_ATTRIBUTES,
  ...AUDIO_TAG_ATTRIBUTES,
  ...A_TAG_ATTRIBUTES,
  ...BUTTON_TAG_ATTRIBUTES,
  ...FORM_TAG_ATTRIBUTES,
  ...IFRAME_TAG_ATTRIBUTES,
  ...IMG_TAG_ATTRIBUTES,
  ...INPUT_TAG_ATTRIBUTES,
];
